apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: productpage-retries
spec:
  hosts:
  - productpage
  http:
  - route:
    - destination:
        host: productpage
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: gateway-error,connect-failure,refused-stream

